before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: kvX6qKSXa0meC9iMBGbXivuWiXUzjyafakHSBT4LdXH6AVmtRXErcOKUmIcbUElQN3xKD0Z25+81ngmyAk7CvyLNSQ6/Jgl4snQgfwmSAnNQ4mFsOXljm3R6MiSb8J/d0HUWYzUScqPPPgeG0ZLp/NtJA5reub1/BRO/QQ9CvQtPZsI5Dz8fZiHCuKdnTPF9onID57yf0Z6KLolqmS0M5KB7Mop58dRkt3c3uHQcmxnZQrSX0FwfzuEXEYouUuVwkM2tbLzk6lMF5HiddHsm/nJqgZllTRpho4nRCePLbyQCQww1Z6CkNKtSElXBxXYZb+7lq/QS2+xy2kbq1wxR3JwSkN40DKebU7PuUdxz1kl3iRILLzVbAMWcydvTnomioQRt9wb5pX8yyLo0KCFeIVn23z0ovLFUW0tHnEnAV3b3KokpIDAlfx4SCfAWTdtinfqcdB1EWpItXLdB+VXemVbT/LOd30Sc7zJsev5ihytNAbFaGpW74WAW4uDsSG6Bsk1SHaKAdXCQqsIAL0ZuSWfH1ZLHtApXHTTQHWk3Ba1TtOtF77KymJgL5TYIfKNoV4k445h+BmwtQFc5AwWLjbLmzTTtIldabKmnopOm0Zqjz0mXSfkq4WSvsdWeHy/QPgXtAJ2XBsrtfD73ovlCXWLiMECFOiVtJqNp0WperO8= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
